import * as version from '../../../../src/version.GENERATED';
import { Component, OnInit, forwardRef } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Router, NavigationEnd, ActivatedRoute } from '@angular/router';
import { filter, map, mergeMap } from 'rxjs/operators';
import { CacheApiService } from '../../../../src/app/services/cache-api.service';
import { RegCacheService } from './services/reg-cache.service';
import { CachePayLoad } from '../../../../src/app/models/cache-api.model';
import { Registrant } from './modules/registration/models/registrant.model';
import { ControlContainer, NgForm } from '@angular/forms';
import { RegistrationDataService } from './services/registration-data.service';
import { Base } from 'moh-common-lib/models';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [
    { provide: ControlContainer, useExisting: forwardRef(() => NgForm) }
  ]
})
export class AppComponent extends Base implements OnInit {
  title = 'Prime';
  registrant = new Registrant();

  constructor( private router: Router,
               private activatedRoute: ActivatedRoute,
               private titleService: Title,
               private cacheApiService: CacheApiService,
               private regCache: RegCacheService,
               private registrationDataService: RegistrationDataService ) {

    super();
  }

  ngOnInit() {
    // This line was AUTO-GENERATED by moh-common-schematics:version-js. Feel free to move this line and/or delete the comment.
    version.success
      ? console.log('%c' + version.message, 'color: #036; font-size: 20px;')
      : console.error(version.message);

    // session ID to track events
    this.registrationDataService.eventUUID = this.objectId;

    this.updateTitleOnRouteChange();

    this.loadCache();
  }

  /**
   * Listen to every route change, and update the page title based on the
   * 'title' property in the route's data.
   */
  private updateTitleOnRouteChange() {
    this.router.events
      .pipe(
        filter(event => event instanceof NavigationEnd),
        map(() => this.activatedRoute),
        map(route => {
          while (route.firstChild) {
            route = route.firstChild;
          }
          return route;
        }),
        filter(route => route.outlet === 'primary'),
        mergeMap(route => route.data)
      )
      .subscribe((data: { title?: string }) => {
        this.setTitle(data.title);
      });
  }

  /** Set the page title. Includes basic formatting and fallback */
  private setTitle(title?: string) {
    if (title) {
      this.titleService.setTitle(`Prime | ${title}`);
    } else {
      // Default title
      this.titleService.setTitle(this.title);
    }
  }


  private loadCache() {
    console.log( 'Load registration cache!' );

    // Load countries for address component
    this.cacheApiService.getCache( 'countries' ).subscribe(
      (response) => {
        const payload = new CachePayLoad( response );
        if ( payload.success ) {
          this.regCache.countryList = payload.country;
        } else {
          console.log( 'Failed to retrieve list of countries.' );
        }
    });

    // Load provinces for address component
    this.cacheApiService.getCache( 'provinces' ).subscribe(
      (response) => {
        const payload = new CachePayLoad( response );
        if ( payload.success ) {
          this.regCache.provinceList = payload.province;
        } else {
          console.log( 'Failed to retrieve list of province.' );
        }
    });

    // Load provinces for address component
    this.cacheApiService.getCache( 'messages' ).subscribe(
      (response) => {
        const payload = new CachePayLoad( response );
        if ( payload.success ) {
          this.regCache.enhancedMsgList = payload.messages;
        } else {
          console.log( 'Failed to retrieve list of enhance messages.' );
        }
    });

    // Load secuiity questions for account component
    this.cacheApiService.getCache( 'securityQues' ).subscribe(
      (response) => {
        const payload = new CachePayLoad( response );
        if ( payload.success ) {
          this.regCache.secQuestionList = payload.secQues;
        } else {
          console.log( 'Failed to retrieve list of security questions.' );
        }
    });

    // Load secuiity questions for account component
    this.cacheApiService.getCache( 'docTypes' ).subscribe(
      (response) => {
        const payload = new CachePayLoad( response );
        if ( payload.success ) {
          this.regCache.documentTypes = payload.documentType;
        } else {
          console.log( 'Failed to retrieve list of security questions.' );
        }
    });
  }
}
